[package]
name = "helium-load"
version = "0.1.0"
authors = ["chris <chris@chrisbruce.com>"]
edition = "2018"

[dependencies]
clap = "*"
dotenv = "*"
helium-wallet = { git = "https://github.com/helium/helium-wallet-rs.git" }
rand = "0.7.3"
tokio = "0.2.11"