[package]
name = "helium-load"
version = "0.1.0"
authors = ["chris <chris@chrisbruce.com>"]
edition = "2018"

[dependencies]
helium = { git = "https://github.com/chrisabruce/helium-rs" }
rand = "0.7.3"
tokio = "0.2.11"
clap = "*"